#!/usr/bin/env python3

import argparse
import os
from pathlib import Path
import subprocess
import sys


def parse_args():
    home = os.getenv("HOME")
    if home is None:
        raise RuntimeError("Couldn't infer home directory from $HOME")
    default_archive_name = '{hostname}_home_{now:%Y_%m_%d_%H_%M_%S}'
    default_exclude_file = Path(home) / "dotfiles" / "borgbackup_exclude_list"
    parser = argparse.ArgumentParser(description='Runs Borgbackup on your home directory with proper flags.')
    parser.add_argument('borg_repo', help='Repository to write to')
    parser.add_argument('--archive_name', metavar='archive_name', default=default_archive_name, help=f'Archive name/formatter')
    parser.add_argument('--exclude_file', metavar='exclude_file', default=default_exclude_file, type=str, nargs='?',
            help=f'File containing exclusion patterns (default: {default_exclude_file})')
    parser.add_argument('--borg_flags', metavar='borg_flags', default=[], help='Extra flags to pass to borg', action='append')
    return parser.parse_args()


def run_backup(borg_repo, archive_name, exclude_file, borg_flags):
    args = ['borg', 'create', '--verbose', '--compression=auto,zstd,6', '--progress', '--stats'] + borg_flags
    home_dir = os.getenv("HOME")
    args += [f'--exclude-from={exclude_file}', f'{borg_repo}::{archive_name}', '.']
    print(f'Running: {args} from {home_dir}')
    result = subprocess.run(args, cwd=home_dir, stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr)
    sys.exit(result.returncode)


if __name__=='__main__':
    args = parse_args()
    run_backup(args.borg_repo, args.archive_name, args.exclude_file, args.borg_flags)
